---
# defaults file for flatpaks

# flatpaks_install_method_default: Defines the default installation method for flatpaks.
# Accepts 'user' or 'system'. Individual flatpak entries in flatpaks_packages_to_install
# can override this default.
flatpaks_install_method_default: "user"
