#SPDX-License-Identifier: MIT-0
---
# tasks file for ffmpeg_full

- name: Include tasks to swap to full ffmpeg
  ansible.builtin.include_tasks: swap_ffmpeg.ansible.yml
  when: ansible_facts['distribution'] == 'Fedora'
