# SPDX-License-Identifier: MIT-0
galaxy_info:
  author: Guillaume Andre (@guiand888)
  description: Install and manage YUM/DNF repository configuration files on Fedora/RHEL systems
  company: personal

  license: GPL-3.0-only

  min_ansible_version: "2.12"

  galaxy_tags:
    - yum
    - dnf
    - fedora
    - rhel
    - repository
    - package
    - configuration

dependencies: []
