---

- name: Install Flatpak packages
  community.general.flatpak:
    name: "{{ item.name }}"
    state: present
    method: "{{ item.method | default(flatpaks_install_method_default) }}"
  loop: "{{ flatpaks_packages_to_install }}"
  loop_control:
    label: "{{ item.name }}"
  when: flatpaks_packages_to_install | length > 0
