---
# Add flathub-beta system remote
- name: Add flathub-beta flatpak remote (system)
  community.general.flatpak_remote:
    name: flathub-beta
    state: present
    flatpakrepo_url: https://dl.flathub.org/beta-repo/flathub-beta.flatpakrepo
    method: system
  ignore_errors: "{{ ansible_check_mode }}"

# Add flathub user remote
- name: Add flathub flatpak remote (user)
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
  become: false
  ignore_errors: "{{ ansible_check_mode }}"
