# SPDX-License-Identifier: MIT-0
---
# handlers file for yum_repos

- name: Refresh DNF cache
  ansible.builtin.command: dnf makecache
  become: true
  listen: refresh yum repos cache
  when: yum_repos_refresh_cache | bool
  changed_when: true
