# SPDX-License-Identifier: MIT-0
---
# handlers file for yum_repos

- name: Refresh DNF cache
  ansible.builtin.dnf:
    update_cache: true
  become: true
  listen: refresh yum repos cache
  when: yum_repos_refresh_cache | bool
